import { Component } from '@angular/core';

@Component({
  selector: 'pko-create',
  templateUrl: './create.component.html',
  styleUrls: ['./create.component.scss'],
})
export class CreateComponent {
  categories = [
    {
      name: 'for sale',
      categories: [
        'antiques',
        'appliances',
        'arts+crafts',
        'atv/utv/sno',
        'auto parts',
        'aviation',
        'baby+kid',
        'barter',
        'beauty+hlth',
        'bike parts',
        'bikes',
        'boat parts',
        'boats',
        'books',
        'business',
        'cars+trucks',
        'cds/dvd/vhs',
        'cell phones',
        'clothes+acc',
        'collectibles',
        'computer parts',
        'computers',
        'electronics',
        'farm+garden',
        'free',
        'furniture',
        'garage sale',
        'general',
        'heavy equip',
        'household',
        'jewelry',
        'materials',
        'motorcycle parts',
        'motorcycles',
        'music instr',
        'photo+video',
        'rvs+camp',
        'sporting',
        'tickets',
        'tools',
        'toys+games',
        'trailers',
        'video gaming',
        'wanted',
        'wheels+tires',
      ],
      isSelected: false,
    },
    {
      name: 'jobs',
      categories: [
        'accounting+finance',
        'admin / office',
        'arch / engineering',
        'art / media / design',
        'biotech / science',
        'business / mgmt',
        'customer service',
        'education',
        'etc / misc',
        'food / bev / hosp',
        'general labor',
        'government',
        'human resources',
        'legal / paralegal',
        'manufacturing',
        'marketing / pr / ad',
        'medical / health',
        'nonprofit sector',
        'real estate',
        'retail / wholesale',
        'sales / biz dev',
        'salon / spa / fitness',
        'security',
        'skilled trade / craft',
        'software / qa / dba',
        'systems / network',
        'technical support',
        'transport',
        'tv / film / video',
        'web / info design',
        'writing / editing',
      ],
      isSelected: false,
    },
    {
      name: 'community',
      categories: [
        'activities',
        'artists',
        'childcare',
        'classes',
        'events',
        'general',
        'groups',
        'local news',
        'lost + found',
        'missed',
        'connections',
        'musicians',
        'pets',
        'politics',
        'rideshare',
        'volunteers',
      ],
      isSelected: false,
    },
    {
      name: 'services',
      categories: [
        'automotive',
        'beauty',
        'cell/mobiles',
        'computer',
        'creative',
        'cycle',
        'event',
        'farm + garden',
        'financial',
        'health/well',
        'household',
        'labor/move',
        'legal',
        'lessons',
        'marine',
        'pet',
        'real estate',
      ],
      isSelected: false,
    },

    {
      name: 'housing',
      categories: [
        'apts / housing',
        'housing swap',
        'housing wanted',
        'office / commercial',
        'parking / storage',
        'real estate for sale',
        'rooms / shared',
        'rooms wanted',
        'sublets / temporary',
        'vacation rentals',
      ],
      isSelected: false,
    },
    {
      name: 'discussion forms',
      categories: [
        'technology',
        'relationships',
        'events',
        'careers',
        'crypto',
        'stock market',
        'news',
        'movies',
        'series',
        'anime',
        'webtoons',
      ],
      isSelected: false,
    },
    {
      name: 'freelance',
      categories: [],
    },
  ];
  selected: any = null;
  setSelected(args: any) {
    this.selected = args;
    this.categories.forEach((category) => {
      category.isSelected = false;
      if (args === category) {
        category.isSelected = !category.isSelected;
      }
    });
  }
}
